name: dedup

# 触发条件
on:
  push:
    tags:        
      - update **

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@v2
      - name: 安装Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: 执行任务
        run: |
          python ./dedup.py
      - name: 提交更改
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./data
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S')去重节点"

      - name: 推送更改
        uses: ad-m/github-push-action@master
        with:
          # github_token: ${{ secrets.TOKEN }}
          branch: main
